---
name: "Build"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up JDK 23"
      uses: "actions/setup-java@v4"
      with:
        distribution: "zulu"
        java-version: "23"
        java-package: "jdk"
        cache: "maven"
    - name: "Set up Maven"
      uses: "stCarolas/setup-maven@v5"
      with:
        maven-version: "3.9.9"
    - run: "mvn clean spotless:check install"
